name: Vale Docs Linting
on:
  push:
  # paths = lista de diretórios que se tiverem alterações dispararão o check na PR
  # não confundir com paths passados para o comando `vale`, ainda que provavelmente
  # sejam idênticos
    paths:
      - 'docs/spec/endpoints/applications/schemas/**.yaml'
      - 'docs/spec/endpoints/cronjobs/schemas/**.yaml'
 
jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Run Vale linter
    run: >
      docker run \
      -v $(pwd)/./:/docs-vale-action \
      -w /docs-vale-action \
      jdkato/vale:v2.11.2 --minAlertLevel error $(pwd)/docs/spec/endpoints/applications/schemas $(pwd)/docs/spec/endpoints/cronjobs/schemas

# name: Linting
# on:
#   pull_requestle:
#     branches: [ master ]

# jobs:
#   prose:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@master

#     - name: Vale
#       uses: errata-ai/vale-action@v1.4.2
#       with:
#         # Optional
#         styles: |
#           https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
#           https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip

#         # Optional
#         config: https://raw.githubusercontent.com/errata-ai/vale/master/.vale.ini

#         # Optional
#         files: path/to/lint
#       env:
#         # Required, set by GitHub actions automatically:
#         # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
#         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}