name: Vale Docs Linting
on:
  push:
  # paths = lista de diretórios que se tiverem alterações dispararão o check na PR
  # não confundir com paths passados para o comando `vale`, ainda que provavelmente
  # sejam idênticos
    paths:
      - 'docs/spec/endpoints/applications/schemas/**.yaml'
      - 'docs/spec/endpoints/cronjobs/schemas/**.yaml'
 
jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Run Vale linter
      run:
        docker run -v $(pwd):/docs-vale-action -w /docs-vale-action jdkato/vale:v2.11.2 --minAlertLevel error docs/spec/endpoints/applications/schemas/ docs/spec/endpoints/cronjobs/schemas/